# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0011_auto_20160128_0006'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Legislator',
            new_name='FedCongressPerson',
        ),
    ]
