# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0013_auto_20160223_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fedcongressperson',
            name='contact_form',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fedcongressperson',
            name='crp_id',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fedcongressperson',
            name='district',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fedcongressperson',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fedcongressperson',
            name='govtrack_id',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fedcongressperson',
            name='leadership_role',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fedcongressperson',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fedcongressperson',
            name='name_suffix',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fedcongressperson',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fedcongressperson',
            name='oc_email',
            field=models.EmailField(blank=True, default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fedcongressperson',
            name='ocd_id',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fedcongressperson',
            name='office',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fedcongressperson',
            name='state_name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fedcongressperson',
            name='term_end',
            field=models.DateField(blank=True, default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fedcongressperson',
            name='term_start',
            field=models.DateField(blank=True, default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fedcongressperson',
            name='thomas_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fedcongressperson',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fedcongressperson',
            name='website',
            field=models.URLField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statecongressperson',
            name='district',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statecongressperson',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statecongressperson',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statecongressperson',
            name='name_suffix',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statecongressperson',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statecongressperson',
            name='office',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statecongressperson',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statecongressperson',
            name='state_name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statecongressperson',
            name='term_end',
            field=models.DateField(blank=True, default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statecongressperson',
            name='term_start',
            field=models.DateField(blank=True, default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statecongressperson',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statecongressperson',
            name='website',
            field=models.URLField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statecongresspersonrole',
            name='end_date',
            field=models.DateField(blank=True, default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statecongresspersonrole',
            name='start_date',
            field=models.DateField(blank=True, default='1900-01-01'),
            preserve_default=False,
        ),
    ]
