# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislators', '0014_auto_20160223_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fedcongressperson',
            name='term_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fedcongressperson',
            name='term_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fedcongressperson',
            name='thomas_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statecongressperson',
            name='term_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statecongressperson',
            name='term_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statecongresspersonrole',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statecongresspersonrole',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
